version: '3'
services:
  # postgres instance that will host our schema & data
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password

  # postgrest instance that will generate and expose the REST interface
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
    depends_on:
      - db

  # Swagger-UI, so we can easily explore the REST interface
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

  # Python / jupyter notebook interface so we can manipulate the database and
  # REST interface arbitrarily
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8999:8999"
    expose:
      - "8999"
    links:
      - db:db
      - server:server
    volumes:
      - ./notebooks:/notebooks
